# Generated by Django 3.2.7 on 2021-11-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_realizacion',
            name='fecha_inicial',
            field=models.DateField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='test_realizacion',
            name='fecha_last_update',
            field=models.DateTimeField(null=True),
        ),
    ]
